// (C)2006 S2 Games
// c_interfacemanager.h
//
//=============================================================================
#ifndef __C_INTERFACEMANAGER_H__
#define __C_INTERFACEMANAGER_H__

//=============================================================================
// Headers
//=============================================================================
#include "../game_shared/c_teaminfo.h"
#include "../k2/i_widget.h"
#include "../k2/c_uitrigger.h"
//=============================================================================

//=============================================================================
// Declarations
//=============================================================================
class CUITrigger;
class CSmartGameUITrigger;
class CMatchStatRecord;

extern CCvarui cg_buildingAttackAlertTime;
//=============================================================================

//=============================================================================
// Definitions
//=============================================================================
const int MAX_DISPLAY_BUFFS(5);
const int MAX_DISPLAY_DEBUFFS(5);
const int MAX_DISPLAY_PLAYERS(25);
const int MAX_DISPLAY_SQUAD(4);
const int MAX_DISPLAY_ITEM_SHOP(15);
const int MAX_WORKER_ICONS(3);
const int MAX_DISPLAY_GADGETS(4);

const int MAX_MAJOR_BUILDING_INFO(4);
const int MAX_MAIN_BUILDING_INFO(5);
const int MAX_MINOR_BUILDING_INFO(5);
const int MAX_MINE_BUILDING_INFO(6);
const int START_MAJOR_BUILDING_INFO(0);
const int START_MAIN_BUILDING_INFO(START_MAJOR_BUILDING_INFO + MAX_MAJOR_BUILDING_INFO);
const int START_MINOR_BUILDING_INFO(START_MAIN_BUILDING_INFO + MAX_MAIN_BUILDING_INFO);
const int START_MINE_BUILDING_INFO(START_MINOR_BUILDING_INFO + MAX_MINOR_BUILDING_INFO);
const int MAX_BUILDING_INFO(MAX_MAJOR_BUILDING_INFO + MAX_MAIN_BUILDING_INFO + MAX_MINOR_BUILDING_INFO + MAX_MINE_BUILDING_INFO);

const int MAX_SELECTED_UNITS(10);

enum EGameUITrigger
{
    UITRIGGER_GAME_TIP_VISIBLE,
    UITRIGGER_GAME_TIP_TEXT,
    UITRIGGER_HEALTH_VALUE,
    UITRIGGER_MANA_VALUE,
    UITRIGGER_STAMINA_VALUE,
    UITRIGGER_HEALTH_PERCENT,
    UITRIGGER_MANA_PERCENT,
    UITRIGGER_STAMINA_PERCENT,
    UITRIGGER_SOUL_COUNT,
    UITRIGGER_SELECTED_ITEM,
    UITRIGGER_PLAYER_NAME_PERSISTANT,
    UITRIGGER_HAS_COMMANDER,

    UITRIGGER_DASH_REMAINING,
    UITRIGGER_DASH_COOLDOWN,

    UITRIGGER_PERSISTANT_STAT,

    UITRIGGER_INVENTORY_COUNT,
    UITRIGGER_INVENTORY_EXISTS,
    UITRIGGER_INVENTORY_ENTITY,
    UITRIGGER_INVENTORY_ICON,
    UITRIGGER_INVENTORY_TIMER,
    UITRIGGER_INVENTORY_ENABLED,
    UITRIGGER_INVENTORY_AMMO_PERCENT,
    UITRIGGER_INVENTORY_AMMO_COUNT,
    UITRIGGER_INVENTORY_LOW_MANA,
    UITRIGGER_INVENTORY_NO_ACCESS,
    UITRIGGER_INVENTORY_DISABLED,
    UITRIGGER_INVENTORY_MELEE,
    UITRIGGER_INVENTORY_RANGED_AMMO,
    UITRIGGER_INVENTORY_RANGED_MANA,
    UITRIGGER_INVENTORY_RANGED_ATTACK_SPEED,
    UITRIGGER_INVENTORY_ABILITY,
    UITRIGGER_INVENTORY_NAME,
    UITRIGGER_INVENTORY_DESCRIPTION,
    UITRIGGER_INVENTORY_MANA_COST,
    UITRIGGER_INVENTORY_COOLDOWN,
    UITRIGGER_INVENTORY_RANGED_DAMAGE,
    UITRIGGER_INVENTORY_AMMO,
    UITRIGGER_INVENTORY_QUICK_ATTACK_DAMAGE,
    UITRIGGER_INVENTORY_QUICK_ATTACK_SPEED,
    UITRIGGER_INVENTORY_STRONG_ATTACK_DAMAGE,
    UITRIGGER_INVENTORY_STRONG_ATTACK_SPEED,
    UITRIGGER_INVENTORY_TYPE,
    UITRIGGER_INVENTORY_PREREQUISITE,

    UITRIGGER_CONSUMABLE_ITEM_ICON,
    UITRIGGER_CONSUMABLE_ITEM_NAME,
    UITRIGGER_CONSUMABLE_ITEM_AVAILABLE,
    
    UITRIGGER_PERSISTANT_VAULT_ICON,

    UITRIGGER_BUFF_ACTIVE,
    UITRIGGER_BUFF_ICON,
    UITRIGGER_BUFF_TIME,
    UITRIGGER_BUFF_TIME_PERCENT,

    UITRIGGER_DEBUFF_ACTIVE,
    UITRIGGER_DEBUFF_ICON,
    UITRIGGER_DEBUFF_TIME,
    UITRIGGER_DEBUFF_TIME_PERCENT,

    UITRIGGER_CURSOR,

    UITRIGGER_LEVEL,
    UITRIGGER_EXPERIENCE,
    UITRIGGER_GOLD,
    UITRIGGER_NAME,
    UITRIGGER_ENTITY,
    UITRIGGER_CLASS,
    UITRIGGER_PLAYER_DESCRIPTION,
    UITRIGGER_SQUAD_COLOR,
    UITRIGGER_SQUAD_COUNT,
    UITRIGGER_SQUAD_OFFICER,

    UITRIGGER_GADGET_ACTIVE,
    UITRIGGER_GADGET_ICON,
    UITRIGGER_GADGET_TIMER,
    UITRIGGER_GADGET_LIFETIME_PERCENT,
    UITRIGGER_GADGET_HEALTH_PERCENT,
    UITRIGGER_GADGET_EXPERIENCE,
    UITRIGGER_GADGET_COUNTER_LABEL,
    UITRIGGER_GADGET_COUNTER_VALUE,
    UITRIGGER_GADGET_ALERT,

    UITRIGGER_TEAM_GOLD,
    UITRIGGER_TEAM_MANA,
    UITRIGGER_TEAM_MANA_PERCENT,
    UITRIGGER_TEAM_MAX_MANA,
    UITRIGGER_TEAM_EXPERIENCE,
    UITRIGGER_TEAM_SKILL_FACTOR,
    UITRIGGER_INCOME,
    UITRIGGER_UPKEEP,
    UITRIGGER_TOTAL_UPKEEP,
    UITRIGGER_COMMAND_CENTER_HEALTH_PERCENT,
    UITRIGGER_ENEMY_COMMAND_CENTER_HEALTH_PERCENT,
    UITRIGGER_BUILDING_ATTACK_ALERT,
    UITRIGGER_SUDDEN_DEATH_ALERT,

    UITRIGGER_STAT_POINTS,
    UITRIGGER_STAT_NAME,
    UITRIGGER_STAT_PERCENT,
    UITRIGGER_STAT_COST,
    UITRIGGER_STAT_BUTTON,
    UITRIGGER_STAT_LEVEL,
    UITRIGGER_STAT_EFFECT,

    UITRIGGER_BASE_MAX_HEALTH,
    UITRIGGER_BASE_MAX_MANA,
    UITRIGGER_BASE_MAX_STAMINA,
    UITRIGGER_ADJUSTED_MAX_HEALTH,
    UITRIGGER_ADJUSTED_MAX_MANA,
    UITRIGGER_ADJUSTED_MAX_STAMINA,
    UITRIGGER_MAX_HEALTH_BONUS,
    UITRIGGER_MAX_MANA_BONUS,
    UITRIGGER_MAX_STAMINA_BONUS,

    UITRIGGER_BASE_HEALTH_REGEN,
    UITRIGGER_BASE_MANA_REGEN,
    UITRIGGER_BASE_STAMINA_REGEN,
    UITRIGGER_ADJUSTED_HEALTH_REGEN,
    UITRIGGER_ADJUSTED_MANA_REGEN,
    UITRIGGER_ADJUSTED_STAMINA_REGEN,
    UITRIGGER_HEALTH_REGEN_BONUS,
    UITRIGGER_MANA_REGEN_BONUS,
    UITRIGGER_STAMINA_REGEN_BONUS,

    UITRIGGER_MELEE_QUICK_DAMAGE,
    UITRIGGER_MELEE_STRONG_DAMAGE,
    UITRIGGER_RANGED1_DAMAGE,
    UITRIGGER_RANGED2_DAMAGE,
    UITRIGGER_RANGED1_SPEED,
    UITRIGGER_RANGED2_SPEED,

    UITRIGGER_BASE_ARMOR,
    UITRIGGER_BASE_ARMOR_REDUCTION,
    UITRIGGER_ADJUSTED_ARMOR,
    UITRIGGER_ADJUSTED_ARMOR_REDUCTION,
    UITRIGGER_ARMOR_BONUS,
    UITRIGGER_ARMOR_REDUCTION_BONUS,

    UITRIGGER_BASE_SPEED,
    UITRIGGER_CURRENT_SPEED,

    UITRIGGER_RACE,
    UITRIGGER_TEAM,
    UITRIGGER_LOADOUT_TIME,
    UITRIGGER_DEATH_TIME,
    UITRIGGER_DEATH_PERCENT,
    UITRIGGER_ECONOMY_INTERVAL,

    UITRIGGER_HOVER_INDEX,
    UITRIGGER_HOVER_NAME,
    UITRIGGER_HOVER_RACE,
    UITRIGGER_HOVER_CLASS,
    UITRIGGER_HOVER_DESCRIPTION,
    UITRIGGER_HOVER_ICON,
    UITRIGGER_HOVER_LEVEL,
    UITRIGGER_HOVER_EXPERIENCE,
    UITRIGGER_HOVER_GOLD,
    UITRIGGER_HOVER_COLORS,

    UITRIGGER_HOVER_HEALTH_VALUE,
    UITRIGGER_HOVER_HEALTH_PERCENT,
    UITRIGGER_HOVER_MAX_HEALTH,

    UITRIGGER_HOVER_MANA_VALUE,
    UITRIGGER_HOVER_MANA_PERCENT,
    UITRIGGER_HOVER_MAX_MANA,

    UITRIGGER_HOVER_STAMINA_VALUE,
    UITRIGGER_HOVER_STAMINA_PERCENT,
    UITRIGGER_HOVER_MAX_STAMINA,

    UITRIGGER_HOVER_LIFETIME_VALUE,
    UITRIGGER_HOVER_LIFETIME_PERCENT,

    UITRIGGER_HOVER_SOUL_COUNT,

    UITRIGGER_HOVER_INVENTORY_EXISTS,
    UITRIGGER_HOVER_INVENTORY_ICON,
    UITRIGGER_HOVER_INVENTORY_AMMO_COUNT,
    UITRIGGER_HOVER_INVENTORY_OVERLAY,

    UITRIGGER_HOVER_BUFF_ACTIVE,
    UITRIGGER_HOVER_BUFF_ICON,
    UITRIGGER_HOVER_DEBUFF_ACTIVE,
    UITRIGGER_HOVER_DEBUFF_ICON,

    UITRIGGER_HOVER_MELEE_QUICK_DAMAGE,
    UITRIGGER_HOVER_MELEE_STRONG_DAMAGE,
    UITRIGGER_HOVER_RANGED1_DAMAGE,
    UITRIGGER_HOVER_RANGED2_DAMAGE,

    UITRIGGER_HOVER_ARMOR,
    UITRIGGER_HOVER_ARMOR_REDUCTION,

    UITRIGGER_HOVER_MODEL,
    UITRIGGER_HOVER_COMMANDER_PORTRAIT,

    UITRIGGER_HOVER_BUILD_PERCENT,

    UITRIGGER_HOVER_GOLD_PERCENT,
    UITRIGGER_HOVER_MAX_GOLD,
    UITRIGGER_HOVER_GOLD_VALUE,
    UITRIGGER_HOVER_EXTRACTION_RATE,
    UITRIGGER_HOVER_UPKEEP_COST,
    UITRIGGER_HOVER_UPKEEP_ACTIVE,

    UITRIGGER_COMMSELECTION_INDEX,
    UITRIGGER_COMMSELECTION_NAME,
    UITRIGGER_COMMSELECTION_RACE,
    UITRIGGER_COMMSELECTION_CLASS,
    UITRIGGER_COMMSELECTION_DESCRIPTION,
    UITRIGGER_COMMSELECTION_ICON,
    UITRIGGER_COMMSELECTION_LEVEL,
    UITRIGGER_COMMSELECTION_EXPERIENCE,
    UITRIGGER_COMMSELECTION_GOLD,
    UITRIGGER_COMMSELECTION_COLORS,

    UITRIGGER_COMMSELECTION_HEALTH_VALUE,
    UITRIGGER_COMMSELECTION_HEALTH_PERCENT,
    UITRIGGER_COMMSELECTION_MAX_HEALTH,

    UITRIGGER_COMMSELECTION_MANA_VALUE,
    UITRIGGER_COMMSELECTION_MANA_PERCENT,
    UITRIGGER_COMMSELECTION_MAX_MANA,

    UITRIGGER_COMMSELECTION_STAMINA_VALUE,
    UITRIGGER_COMMSELECTION_STAMINA_PERCENT,
    UITRIGGER_COMMSELECTION_MAX_STAMINA,

    UITRIGGER_COMMSELECTION_LIFETIME_VALUE,
    UITRIGGER_COMMSELECTION_LIFETIME_PERCENT,

    UITRIGGER_COMMSELECTION_SOUL_COUNT,

    UITRIGGER_COMMSELECTION_INVENTORY_EXISTS,
    UITRIGGER_COMMSELECTION_INVENTORY_ICON,
    UITRIGGER_COMMSELECTION_INVENTORY_AMMO_COUNT,
    UITRIGGER_COMMSELECTION_INVENTORY_OVERLAY,

    UITRIGGER_COMMSELECTION_BUFF_ACTIVE,
    UITRIGGER_COMMSELECTION_BUFF_ICON,
    UITRIGGER_COMMSELECTION_DEBUFF_ACTIVE,
    UITRIGGER_COMMSELECTION_DEBUFF_ICON,

    UITRIGGER_COMMSELECTION_MELEE_QUICK_DAMAGE,
    UITRIGGER_COMMSELECTION_MELEE_STRONG_DAMAGE,
    UITRIGGER_COMMSELECTION_RANGED1_DAMAGE,
    UITRIGGER_COMMSELECTION_RANGED2_DAMAGE,

    UITRIGGER_COMMSELECTION_ARMOR,
    UITRIGGER_COMMSELECTION_ARMOR_REDUCTION,

    UITRIGGER_COMMSELECTION_MODEL,
    UITRIGGER_COMMSELECTION_COMMANDER_PORTRAIT,

    UITRIGGER_COMMSELECTION_BUILD_PERCENT,

    UITRIGGER_COMMSELECTION_GOLD_PERCENT,
    UITRIGGER_COMMSELECTION_MAX_GOLD,
    UITRIGGER_COMMSELECTION_GOLD_VALUE,
    UITRIGGER_COMMSELECTION_EXTRACTION_RATE,
    UITRIGGER_COMMSELECTION_UPKEEP_COST,
    UITRIGGER_COMMSELECTION_UPKEEP_ACTIVE,

    UITRIGGER_REPAIRABLE,

    UITRIGGER_ALT_INFO_ALLY,
    UITRIGGER_ALT_INFO_NAME,
    UITRIGGER_ALT_INFO_DISTANCE,
    UITRIGGER_ALT_INFO_HEALTH_PERCENT,
    UITRIGGER_ALT_INFO_UPKEEP,
    UITRIGGER_ALT_INFO_BUILD_PERCENT,
    UITRIGGER_ALT_INFO_BUFF_ACTIVE,
    UITRIGGER_ALT_INFO_BUFF_ICON,
    UITRIGGER_ALT_INFO_DEBUFF_ACTIVE,
    UITRIGGER_ALT_INFO_DEBUFF_ICON,

    UITRIGGER_PET_NAME,
    UITRIGGER_PET_ICON,

    UITRIGGER_PET_HEALTH_VALUE,
    UITRIGGER_PET_MANA_VALUE,
    UITRIGGER_PET_HEALTH_PERCENT,
    UITRIGGER_PET_MANA_PERCENT,
    
    UITRIGGER_PET_MAX_HEALTH,
    UITRIGGER_PET_MAX_MANA,
    UITRIGGER_PET_MAX_STAMINA,

    UITRIGGER_PET_ARMOR,
    UITRIGGER_PET_ARMOR_REDUCTION,

    UITRIGGER_OFFICER_SQUAD_NAME,

    UITRIGGER_LOBBY_PHASE,
    UITRIGGER_LOBBY_STATUS,
    UITRIGGER_LOBBY_PHASE_DESCRIPTION,
    UITRIGGER_LOBBY_PHASE_TIMER,
    UITRIGGER_LOBBY_PHASE_INSTRUCTION,
    UITRIGGER_LOBBY_REQUEST_BUTTON,
    UITRIGGER_LOBBY_DECLINE_BUTTON,
    UITRIGGER_LOBBY_TEAM_LIST,
    UITRIGGER_LOBBY_TEAM_CANDIDATE_LIST,
    UITRIGGER_LOBBY_TEAM_BUTTON,
    UITRIGGER_LOBBY_TEAM_OFFICER_DEMOTE_BUTTON,

    UITRIGGER_LOBBY_COMMANDER_VISIBLE,
    UITRIGGER_LOBBY_CANDIDATE_LIST_VISIBLE,
    UITRIGGER_LOBBY_CANDIDATE_LIST_SIZE,
    UITRIGGER_LOBBY_TEAM_LIST_VISIBLE,
    UITRIGGER_LOBBY_TEAM_LIST_SIZE,
    UITRIGGER_LOBBY_TEAM_PLAYER_COUNT,
    UITRIGGER_LOBBY_TEAM_AVERAGE_SF,
    UITRIGGER_LOBBY_TEAM_AVERAGE_LEVEL,
    UITRIGGER_LOBBY_TEAM_RACE,
    UITRIGGER_LOBBY_SPECTATOR_LIST,
    UITRIGGER_LOBBY_SPECTATOR_BUTTON,

    UITRIGGER_LOBBY_OFFICER_VISIBLE,
    UITRIGGER_LOBBY_OFFICER_NAME,
    UITRIGGER_LOBBY_SQUAD_LIST,
    UITRIGGER_LOBBY_SQUAD_LIST_SIZE,
    UITRIGGER_LOBBY_SQUAD_LIST_VISIBLE,
    UITRIGGER_LOBBY_SQUAD_LIST_NAME,
    UITRIGGER_LOBBY_SQUAD_LIST_COLOR,
    UITRIGGER_LOBBY_SQUAD_JOIN_BUTTON,
    UITRIGGER_LOBBY_COMMANDER_NAME,

    UITRIGGER_LOBBY_SERVER_NAME,
    UITRIGGER_LOBBY_SERVER_LOCATION,
    UITRIGGER_LOBBY_SERVER_MAP,
    UITRIGGER_LOBBY_SERVER_STATUS,
    UITRIGGER_LOBBY_SERVER_PLAYERS,
    UITRIGGER_LOBBY_SERVER_MIN_PLAYERS,
    UITRIGGER_LOBBY_SERVER_PING,
    UITRIGGER_LOBBY_SERVER_MAP_VERSION,
    UITRIGGER_LOBBY_SERVER_MATCHES_PLAYED,
    UITRIGGER_LOBBY_SERVER_MIN_KARMA,

    UITRIGGER_SCOREBOARD_PLAYER_ACTIVE,
    UITRIGGER_SCOREBOARD_PLAYER_SQUAD,
    UITRIGGER_SCOREBOARD_PLAYER_OFFICER,
    UITRIGGER_SCOREBOARD_PLAYER_LEVEL,
    UITRIGGER_SCOREBOARD_PLAYER_NAME,
    UITRIGGER_SCOREBOARD_PLAYER_PING,
    UITRIGGER_SCOREBOARD_PLAYER_EXP,
    UITRIGGER_SCOREBOARD_PLAYER_KILLS,
    UITRIGGER_SCOREBOARD_PLAYER_DEATHS,
    UITRIGGER_SCOREBOARD_PLAYER_ASSISTS,
    UITRIGGER_SCOREBOARD_PLAYER_MUTED,
    UITRIGGER_SCOREBOARD_PLAYER_SF,

    UITRIGGER_SCOREBOARD_COMMAND_CENTER_HEALTH_PERCENT,
    UITRIGGER_SCOREBOARD_COMMAND_CENTER_HEALTH_VALUE,
    UITRIGGER_SCOREBOARD_COMMAND_CENTER_HEALTH_MAX,

    UITRIGGER_SCOREBOARD_COMMANDER,
    UITRIGGER_SCOREBOARD_COMMANDER_RECORD,
    UITRIGGER_SCOREBOARD_COMMANDER_SF,

    UITRIGGER_SCOREBOARD_NUM_PLAYERS,

    UITRIGGER_GAME_MATCH_ID,

    UITRIGGER_SQUAD_INFO,
    UITRIGGER_SQUAD_ICON,
    UITRIGGER_SQUAD_NAME,
    UITRIGGER_SQUAD_HEALTH_PERCENT,
    UITRIGGER_SQUAD_MANA_PERCENT,

    UITRIGGER_ENDGAME_TEAM,

    UITRIGGER_ENDGAME_TIME,

    UITRIGGER_ENDGAME_AWARD,
    UITRIGGER_ENDGAME_LIST,

    UITRIGGER_ENDGAME_DATA_EXPERIENCE,
    UITRIGGER_ENDGAME_DATA_KILLS,
    UITRIGGER_ENDGAME_DATA_ASSISTS,
    UITRIGGER_ENDGAME_DATA_DEATHS,
    UITRIGGER_ENDGAME_DATA_KILL_DEATH_RATIO,
    UITRIGGER_ENDGAME_DATA_HP_HEALED,
    UITRIGGER_ENDGAME_DATA_RESURRECTS,
    UITRIGGER_ENDGAME_DATA_GOLD_EARNED,
    UITRIGGER_ENDGAME_DATA_HP_REPAIRED,
    UITRIGGER_ENDGAME_DATA_BUILDINGS_RAZED,
    UITRIGGER_ENDGAME_DATA_PLAYER_DAMAGE,
    UITRIGGER_ENDGAME_DATA_BUILDING_DAMAGE,

    UITRIGGER_ENDGAME_DATA_EXPERIENCE_PAGES,
    UITRIGGER_ENDGAME_DATA_KILLS_PAGES,
    UITRIGGER_ENDGAME_DATA_ASSISTS_PAGES,
    UITRIGGER_ENDGAME_DATA_DEATHS_PAGES,
    UITRIGGER_ENDGAME_DATA_KILL_DEATH_RATIO_PAGES,
    UITRIGGER_ENDGAME_DATA_HP_HEALED_PAGES,
    UITRIGGER_ENDGAME_DATA_RESURRECTS_PAGES,
    UITRIGGER_ENDGAME_DATA_GOLD_EARNED_PAGES,
    UITRIGGER_ENDGAME_DATA_HP_REPAIRED_PAGES,
    UITRIGGER_ENDGAME_DATA_BUILDINGS_RAZED_PAGES,
    UITRIGGER_ENDGAME_DATA_PLAYER_DAMAGE_PAGES,
    UITRIGGER_ENDGAME_DATA_BUILDING_DAMAGE_PAGES,

    UITRIGGER_ENDGAME_RANK,
    UITRIGGER_ENDGAME_NPC_KILLS,
    UITRIGGER_ENDGAME_EXPERIENCE,
    UITRIGGER_ENDGAME_HP_HEALED,
    UITRIGGER_ENDGAME_KILLS,
    UITRIGGER_ENDGAME_RESURRECTS,
    UITRIGGER_ENDGAME_DEATHS,
    UITRIGGER_ENDGAME_BUILDING_DAMAGE,
    UITRIGGER_ENDGAME_KILL_DEATH_RATIO,
    UITRIGGER_ENDGAME_RAZED,
    UITRIGGER_ENDGAME_ASSISTS,
    UITRIGGER_ENDGAME_HP_REPAIRED,
    UITRIGGER_ENDGAME_PLAYER_DAMAGE,
    UITRIGGER_ENDGAME_GOLD_EARNED,
    UITRIGGER_ENDGAME_SOULS_SPENT,
    UITRIGGER_ENDGAME_TIME_PLAYED,
    UITRIGGER_ENDGAME_VICTORY,
    UITRIGGER_ENDGAME_SHOW_STATS,
    UITRIGGER_ENDGAME_MATCH_ID,

    UITRIGGER_BUILDING_INFO_EXISTS,
    UITRIGGER_BUILDING_INFO_INDEX,
    UITRIGGER_BUILDING_INFO_NAME,
    UITRIGGER_BUILDING_INFO_ARMOR,
    UITRIGGER_BUILDING_INFO_ICON,
    UITRIGGER_BUILDING_INFO_HEALTH_PERCENT,
    UITRIGGER_BUILDING_INFO_HEALTH_VALUE,
    UITRIGGER_BUILDING_INFO_MAX_HEALTH,
    UITRIGGER_BUILDING_INFO_UPKEEP_COST,
    UITRIGGER_BUILDING_INFO_UPKEEP_ENABLED,
    UITRIGGER_BUILDING_INFO_EXTRACTION_RATE,
    UITRIGGER_BUILDING_INFO_GOLD_VALUE,
    UITRIGGER_BUILDING_INFO_GOLD_PERCENT,
    UITRIGGER_BUILDING_INFO_MAX_GOLD,
    UITRIGGER_BUILDING_INFO_BUILD_PERCENT,
    UITRIGGER_BUILDING_INFO_REPAIRABLE,

    UITRIGGER_MULTI_SELECT_ACTIVE,
    UITRIGGER_MULTI_SELECT_ICON,
    UITRIGGER_MULTI_SELECT_DEAD,
    UITRIGGER_MULTI_SELECT_HEALTH_PERCENT,
    UITRIGGER_MULTI_SELECT_MANA_PERCENT,
    UITRIGGER_MULTI_SELECT_SQUAD_COLOR,
    UITRIGGER_MULTI_SELECT_INDEX,

    UITRIGGER_COMMANDER_SQUAD_EXISTS,
    UITRIGGER_COMMANDER_SQUAD_COLOR,
    UITRIGGER_COMMANDER_SQUAD_SIZE,
    UITRIGGER_COMMANDER_SQUAD_OFFICER_INDEX,
    UITRIGGER_COMMANDER_SQUAD_OFFICER_ICON,
    UITRIGGER_COMMANDER_SQUAD_OFFICER_HEALTH_PERCENT,
    UITRIGGER_COMMANDER_SQUAD_OFFICER_MANA_PERCENT,
    UITRIGGER_COMMANDER_SQUAD_OFFICER_DEAD,

    UITRIGGER_COMMANDER_SQUAD_MEMBER_ACTIVE,
    UITRIGGER_COMMANDER_SQUAD_MEMBER_INDEX,
    UITRIGGER_COMMANDER_SQUAD_MEMBER_ICON,
    UITRIGGER_COMMANDER_SQUAD_MEMBER_HEALTH_PERCENT,
    UITRIGGER_COMMANDER_SQUAD_MEMBER_MANA_PERCENT,
    UITRIGGER_COMMANDER_SQUAD_MEMBER_DEAD,

    UITRIGGER_COMMANDER_ORDERTIP,
    UITRIGGER_COMMANDER_ORDERTIPVISIBLE,
    UITRIGGER_COMMANDER_ORDERTYPE,
    UITRIGGER_COMMANDER_ORDERDIRECTION,

    UITRIGGER_COMMANDER_WORKER_COOLDOWN,
    UITRIGGER_COMMANDER_WORKER_AVAILABLE,
    UITRIGGER_COMMANDER_WORKER_INDEX,
    UITRIGGER_COMMANDER_WORKER_ICON,
    UITRIGGER_COMMANDER_WORKER_ACTION,
    UITRIGGER_COMMANDER_WORKER_HEALTH,

    UITRIGGER_BUILD_MODE_ACTIVE,
    UITRIGGER_BUILD_FAIL_REASON,
    UITRIGGER_KILL_NOTIFICATION,

    UITRIGGER_VOICE_COMMAND_MAIN,
    UITRIGGER_VOICE_COMMAND_SUB,
    UITRIGGER_VOICE_COMMAND_CATEGORIES,
    UITRIGGER_VOICE_COMMAND_SUB_ITEMS,
    UITRIGGER_VOICE_COMMAND_SUB_TITLE,

    UITRIGGER_LOADOUT_TOOLTIP_VISIBLE,
    UITRIGGER_LOADOUT_TOOLTIP_TITLE,
    UITRIGGER_LOADOUT_TOOLTIP_MESSAGE,
    UITRIGGER_LOADOUT_SPAWN_QUEUE_POSITION,
    UITRIGGER_LOADOUT_SPAWN_QUEUE_SIZE,

    UITRIGGER_REPLAY_NAME,
    UITRIGGER_REPLAY_TIME,
    UITRIGGER_REPLAY_ENDTIME,
    UITRIGGER_REPLAY_FRAME,
    UITRIGGER_REPLAY_ENDFRAME,
    UITRIGGER_REPLAY_SPEED,

    UITRIGGER_WARMUP_PLAYERS_REQUIRED,

    UITRIGGER_DEMO_ACCOUNT,

    NUM_UITRIGGERS
};

typedef vector<CSmartGameUITrigger*>    SmartUITriggerVector;
typedef SmartUITriggerVector::iterator  SmartUITriggerVector_it;
//=============================================================================

//=============================================================================
// CSmartGameUITrigger
//=============================================================================
class CSmartGameUITrigger
{
private:
    uint                m_uiCount;
    uint                m_uiSubCount;

    vector<CUITrigger*> m_vTriggers;
    vector<bool>        m_vTriggerOwner;
    vector<bool>        m_vbValue;
    vector<ushort>      m_vunValue;
    uivector            m_vuiValue;
    fvector             m_vfValue;
    svector             m_vsValue;
    vector<svector>     m_vvValue;

    uivector            m_vUpdateSequence;

    CSmartGameUITrigger();

public:
    ~CSmartGameUITrigger();
    CSmartGameUITrigger(const tstring &sName, uint uiCount, uint uiSubCount);

    void    Trigger(bool bValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Trigger(short nValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Trigger(ushort unValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Trigger(int uiValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Trigger(uint uiValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Trigger(float fValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Trigger(const tstring &sValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Trigger(const TCHAR *szValue, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence)     { Trigger(tstring(szValue), uiIndex, uiSubIndex, uiUpdateSequence); }
    void    Execute(const tstring &sScript, uint uiIndex, uint uiSubIndex);
    void    Trigger(const svector &vParams, uint uiIndex, uint uiSubIndex, uint uiUpdateSequence);
    void    Show(uint uiIndex, uint uiSubIndex);
    void    Hide(uint uiIndex, uint uiSubIndex);
};
//=============================================================================

//=============================================================================
// CGameInterfaceManager
//=============================================================================
class CGameInterfaceManager
{
private:
    SmartUITriggerVector    m_vTriggers;
    tstring                 m_sCurrentCursor;

    uint            m_uiUpdateSequence;
    bool            m_bCursor;
    uint            m_uiCursorUpdateSequence;
    bool            m_bShowScoreOverlay;

    // Cached values
    EGamePhase      m_eGamePhase;
    EGameInterface  m_eCurrentInterface;

    uint            m_uiLastBuildingAttackAlertTime;

    // Special case triggers
    CUITrigger                          m_CanBuild;
    map<const IEntityAllocator *, int>  m_mapCanBuild;

public:
    ~CGameInterfaceManager();
    CGameInterfaceManager();

    void    Init();
    void    ForceUpdate();

    // Trigger management
    void    AddTrigger(uint uiTriggerID, const tstring &sName, uint uiCount = 1, uint uiSubCount = 1);

    void    Execute(uint uiTriggerID, const tstring &sScript, uint uiIndex = 0, uint uiSubIndex = 0)
    {
        PROFILE("CGameInterfaceManager::Execute");
        assert(uiTriggerID < NUM_UITRIGGERS);
        m_vTriggers[uiTriggerID]->Execute(sScript, uiIndex, uiSubIndex);
    }

    template<class T>
    void    Trigger(uint uiTriggerID, T _Param, uint uiIndex = 0, uint uiSubIndex = 0)
    {
        PROFILE("CGameInterfaceManager::Trigger");
        assert(uiTriggerID < NUM_UITRIGGERS);
        m_vTriggers[uiTriggerID]->Trigger(_Param, uiIndex, uiSubIndex, m_uiUpdateSequence);
    }

    void    Trigger(uint uiTriggerID, const tstring &sParam, uint uiIndex = 0, uint uiSubIndex = 0)
    {
        PROFILE("CGameInterfaceManager::Trigger");
        assert(uiTriggerID < NUM_UITRIGGERS);
        m_vTriggers[uiTriggerID]->Trigger(sParam, uiIndex, uiSubIndex, m_uiUpdateSequence);
    }

    void    Trigger(uint uiTriggerID, const svector &vParams, uint uiIndex = 0, uint uiSubIndex = 0)
    {
        PROFILE("CGameInterfaceManager::Trigger");
        assert(uiTriggerID < NUM_UITRIGGERS);
        m_vTriggers[uiTriggerID]->Trigger(vParams, uiIndex, uiSubIndex, m_uiUpdateSequence);
    }

    void    Show(uint uiTriggerID, uint uiIndex = 0, uint uiSubIndex = 0);
    void    Hide(uint uiTriggerID, uint uiIndex = 0, uint uiSubIndex = 0);

    // Update functions
    void    SetPersistantStat(int iStat, int iValue);
    void    ShowStats(int iClientNum);
    void    ShowStatsByTeam(int iTeam, int iPlayer);

    void    SetPersistantVaultIcon(int iVaultNum);

    void    ShowCursor(bool bShow);
    void    SetCursor(const tstring &sName)     { m_sCurrentCursor = sName; ShowCursor(true); }

    void    SetHoverMeleeQuickDamage(float fMin, float fMax);
    void    SetHoverMeleeStrongDamage(float fMin, float fMax);
    void    SetHoverRanged1Damage(float fMin, float fMax);
    void    SetHoverRanged2Damage(float fMin, float fMax);

    bool    LobbyRequiresUpdate();

    void    Update();
    void    UpdatePlayer();
    void    UpdateGameOver();
    void    UpdateInventory();
    void    UpdatePlayerDetails();
    void    UpdateLobby();
    void    UpdateLoadout();
    void    UpdateScores();
    void    UpdateCommander();
    void    UpdateSquad();
    void    UpdateCommanderSquads();
    void    UpdateBuildings();
    void    UpdateBuildButtons();
    void    UpdateHoverInfo(uint uiTargetIndex, bool bShow);
    void    UpdateCommSelectionInfo(uint uiTargetIndex, bool bShow);
    void    UpdateVoiceCommands();
    void    UpdateReplay();
    void    UpdateOfficer();

    void    ShowEndGameStats(int iClientID, int iStart, int iEnd);
    void    GetEndGameDetailStats(EGameUITrigger eTrigger, EGameUITrigger ePageTrigger, const CMatchStatRecord &record, uint uiStart, uint uiEnd);
    void    GetEndGameValueStats(EGameUITrigger eTrigger, EGameUITrigger ePageTrigger, const CMatchStatRecord &record, uint uiStart, uint uiEnd);
    void    GetEndGameTimeStats(EGameUITrigger eTrigger, EGameUITrigger ePageTrigger, const CMatchStatRecord &record, uint uiStart, uint uiEnd);

    void    BuildingAttackAlert(const tstring &sName);

    void    ShowGameTip(const tstring &sMessage);
    void    HideGameTip();

    void    ShowScoreOverlay(bool bShow)        { if (!m_bShowScoreOverlay && bShow) ForceUpdate(); m_bShowScoreOverlay = bShow; }
};
//=============================================================================
#endif //__C_INTERFACEMANAGER_H__
