Import(['getCPPFiles', 'env', 'project', 'build_type', 'arch'])

# precompiled header
env['GchSh'] = env.GchSh(target = '../game_shared_common.h.gch/'+build_type+'-'+arch, source = 'game_shared_common.h')[0]

# libs to link against
if build_type == 'debug':
	env.Append(LIBS=['k2_debug'])
else:
	env.Append(LIBS=['k2'])

# cpp defines
env.Append(CPPDEFINES = ['K2_DLL', 'GAME_SHARED_EXPORTS'])

if build_type == 'debug':
	libname = 'game_shared_debug'
else:
	libname = 'game_shared'

# library search path
env.Append(LIBPATH = ['#k2/'+build_type+'-'+arch])

# source files
src = getCPPFiles('../game_shared.vcproj')

# create the library
env.SharedLibrary(target = libname, source = src)

# dependencies
env.Depends('lib' + libname + '.so', Alias('k2-' + build_type + '-' + arch))

# target
Alias(project + '-' + build_type + '-' + arch, 'lib' + libname + '.so')
