// (C)2008 S2 Games
// c_xmlproc_state.cpp
//
//=============================================================================

//=============================================================================
// Headers
//=============================================================================
#include "game_shared_common.h"

#include "c_statedefinition.h"
#include "i_entitystate.h"

#include "../k2/c_xmlprocroot.h"
//=============================================================================

DEFINE_DEFINITION_TYPE_INFO(CStateDefinition, ENTITY_BASE_TYPE_STATE, State)

/*====================
  CStateDefinition::ReadSettings
  ====================*/
void    CStateDefinition::ReadSettings(CStateDefinition *pDefinition, const CXMLNode &node, bool bMod)
{
    ISlaveDefinition::ReadSettings(pDefinition, node, bMod);

    READ_ENTITY_DEFINITION_PROPERTY(IsHidden, ishidden)
    READ_ENTITY_DEFINITION_PROPERTY(DispelOnDamage, dispelondamage)
    READ_ENTITY_DEFINITION_PROPERTY(DispelOnAction, dispelonaction)
    READ_ENTITY_DEFINITION_PROPERTY(DisplayLevel, displaylevel)
    READ_ENTITY_DEFINITION_PROPERTY(ImpactInterval, impactinterval)
    READ_ENTITY_DEFINITION_PROPERTY(MorphPriority, morphpriority)
    READ_ENTITY_DEFINITION_PROPERTY(NoRefresh, norefresh)
    READ_ENTITY_DEFINITION_PROPERTY(PropagateToIllusions, propagatetoillusions)
    READ_ENTITY_DEFINITION_PROPERTY(DeathPersist, deathpersist)
    READ_ENTITY_DEFINITION_PROPERTY(ServerEntity, serverentity)

    READ_ENTITY_DEFINITION_MULTI_LEVEL_TEMPORAL_PROGRESSIVE_PROPERTY(Armor, armor)
    READ_ENTITY_DEFINITION_MULTI_LEVEL_TEMPORAL_PROGRESSIVE_PROPERTY(MoveSpeedSlow, movespeedslow)
    READ_ENTITY_DEFINITION_MULTI_LEVEL_TEMPORAL_PROGRESSIVE_PROPERTY(MagicArmor, magicarmor)

    READ_ENTITY_DEFINITION_MUTATION(Strength, strength)
    READ_ENTITY_DEFINITION_MUTATION(Agility, agility)
    READ_ENTITY_DEFINITION_MUTATION(Intelligence, intelligence)

    READ_ENTITY_DEFINITION_MUTATION(MaxHealth, maxhealth)
    READ_ENTITY_DEFINITION_MUTATION(HealthRegen, healthregen)
    READ_ENTITY_DEFINITION_MUTATION(MaxMana, maxmana)
    READ_ENTITY_DEFINITION_MUTATION(ManaRegen, manaregen)
    READ_ENTITY_DEFINITION_MUTATION(Armor, armor)
    
    READ_ENTITY_DEFINITION_MUTATION(MagicArmor, magicarmor)
    READ_ENTITY_DEFINITION_MUTATION(MoveSpeed, movespeed)
    READ_ENTITY_DEFINITION_MUTATION(SlowResistance, slowresistance)
    READ_ENTITY_DEFINITION_MUTATION(AttackRange, attackrange)
    READ_ENTITY_DEFINITION_MUTATION(LifeSteal, lifesteal)
    READ_ENTITY_DEFINITION_MUTATION(HealthRegenReduction, healthregenreduction)
    READ_ENTITY_DEFINITION_MUTATION(ManaRegenReduction, manaregenreduction)
    
    READ_ENTITY_DEFINITION_MUTATION(RevealRange, revealrange)

    READ_ENTITY_DEFINITION_MUTATION(UnitType, unittype)
    READ_ENTITY_DEFINITION_MUTATION(Icon, icon)
    READ_ENTITY_DEFINITION_MUTATION(Portrait, portrait)
    READ_ENTITY_DEFINITION_MUTATION(Model, model)
    READ_ENTITY_DEFINITION_MUTATION(MapIconProperty, mapicon)
    READ_ENTITY_DEFINITION_MUTATION(MapIconColorProperty, mapiconcolor)
    READ_ENTITY_DEFINITION_MUTATION(MapIconSizeProperty, mapiconsize)
    READ_ENTITY_DEFINITION_MUTATION(Skin, skin)
    READ_ENTITY_DEFINITION_MUTATION(AttackProjectile, attackprojectile)
    READ_ENTITY_DEFINITION_MUTATION(AttackType, attacktype)
    READ_ENTITY_DEFINITION_MUTATION(AttackEffectType, attackeffecttype)
    READ_ENTITY_DEFINITION_MUTATION(AttackDamageType, attackdamagetype)
    READ_ENTITY_DEFINITION_MUTATION(AttackCooldown, attackcooldown)
    READ_ENTITY_DEFINITION_MUTATION(AttackDuration, attackduration)
    READ_ENTITY_DEFINITION_MUTATION(AttackActionTime, attackactiontime)
    READ_ENTITY_DEFINITION_MUTATION(AttackTargetScheme, attacktargetscheme)
    READ_ENTITY_DEFINITION_MUTATION(AttackNonLethal, attacknonlethal)
    READ_ENTITY_DEFINITION_MUTATION(ThreatEffectType, threateffecttype)
    READ_ENTITY_DEFINITION_MUTATION(ThreatScheme, threatscheme)
    READ_ENTITY_DEFINITION_MUTATION(AggroRange, aggrorange)
    READ_ENTITY_DEFINITION_MUTATION(AggroScheme, aggroscheme)
    READ_ENTITY_DEFINITION_MUTATION(ProximityRange, proximityrange)
    READ_ENTITY_DEFINITION_MUTATION(ProximityScheme, proximityscheme)
    READ_ENTITY_DEFINITION_MUTATION(PreGlobalScale, preglobalscale)
    READ_ENTITY_DEFINITION_MUTATION(EffectScale, effectscale)
    READ_ENTITY_DEFINITION_MUTATION(ModelScale, modelscale)
    READ_ENTITY_DEFINITION_MUTATION(InfoHeight, infoheight)
    READ_ENTITY_DEFINITION_MUTATION(BoundsHeight, boundsheight)
    READ_ENTITY_DEFINITION_MUTATION(BoundsRadius, boundsradius)
    READ_ENTITY_DEFINITION_MUTATION(SelectionRadius, selectionradius)
    READ_ENTITY_DEFINITION_MUTATION(IsSelectable, isselectable)
    READ_ENTITY_DEFINITION_MUTATION(NoCorpse, nocorpse)
    READ_ENTITY_DEFINITION_MUTATION(AttackRangeBuffer, attackrangebuffer)
    READ_ENTITY_DEFINITION_MUTATION(AttackOffset, attackoffset)
    READ_ENTITY_DEFINITION_MUTATION(TargetOffset, targetoffset)
    READ_ENTITY_DEFINITION_MUTATION(AttackStartEffect, attackstarteffect)
    READ_ENTITY_DEFINITION_MUTATION(AttackActionEffect, attackactioneffect)
    READ_ENTITY_DEFINITION_MUTATION(AttackImpactEffect, attackimpacteffect)
    READ_ENTITY_DEFINITION_MUTATION(DeathEffect, deatheffect)
    READ_ENTITY_DEFINITION_MUTATION(PassiveEffect, passiveeffect)
    READ_ENTITY_DEFINITION_MUTATION(SpawnEffect, spawneffect)
    READ_ENTITY_DEFINITION_MUTATION(SightRangeDay, sightrangeday)
    READ_ENTITY_DEFINITION_MUTATION(SightRangeNight, sightrangenight)

    READ_ENTITY_DEFINITION_MUTATION(Inventory0, inventory0)
    READ_ENTITY_DEFINITION_MUTATION(Inventory1, inventory1)
    READ_ENTITY_DEFINITION_MUTATION(Inventory2, inventory2)
    READ_ENTITY_DEFINITION_MUTATION(Inventory3, inventory3)
    READ_ENTITY_DEFINITION_MUTATION(Inventory4, inventory4)
    READ_ENTITY_DEFINITION_MUTATION(Inventory5, inventory5)
    READ_ENTITY_DEFINITION_MUTATION(Inventory6, inventory6)
    READ_ENTITY_DEFINITION_MUTATION(Inventory7, inventory7)
    READ_ENTITY_DEFINITION_MUTATION(Inventory8, inventory8)
    READ_ENTITY_DEFINITION_MUTATION(SharedInventory0, sharedinventory0)
    READ_ENTITY_DEFINITION_MUTATION(SharedInventory1, sharedinventory1)
    READ_ENTITY_DEFINITION_MUTATION(SharedInventory2, sharedinventory2)

    READ_ENTITY_DEFINITION_MUTATION(Invulnerable, invulnerable)
    READ_ENTITY_DEFINITION_MUTATION(ClearVision, clearvision)
    READ_ENTITY_DEFINITION_MUTATION(Deniable, deniable)
    READ_ENTITY_DEFINITION_MUTATION(DeniablePercent, deniablepercent)
    READ_ENTITY_DEFINITION_MUTATION(Smackable, smackable)
    READ_ENTITY_DEFINITION_MUTATION(NoThreat, nothreat)
    READ_ENTITY_DEFINITION_MUTATION(TrueStrike, truestrike)
    READ_ENTITY_DEFINITION_MUTATION(AlwaysTransmitData, alwaystransmitdata)

    READ_ENTITY_DEFINITION_MUTATION(Unitwalking, unitwalking)
    READ_ENTITY_DEFINITION_MUTATION(Treewalking, treewalking)
    READ_ENTITY_DEFINITION_MUTATION(Cliffwalking, cliffwalking)
    READ_ENTITY_DEFINITION_MUTATION(Buildingwalking, buildingwalking)
    READ_ENTITY_DEFINITION_MUTATION(Antiwalking, antiwalking)

    READ_ENTITY_DEFINITION_MUTATION(ShopAccess, shopaccess)
    READ_ENTITY_DEFINITION_MUTATION(RemoteShopAccess, remoteshopaccess)
    READ_ENTITY_DEFINITION_MUTATION(SharedShopAccess, sharedshopaccess)
    READ_ENTITY_DEFINITION_MUTATION(SharedRemoteShopAccess, sharedremoteshopaccess)
    READ_ENTITY_DEFINITION_MUTATION(RestrictItemAccess, restrictitemaccess)
    READ_ENTITY_DEFINITION_MUTATION(StashAccess, stashaccess)

    READ_ENTITY_DEFINITION_MUTATION(DefaultBehavior, defaultbehavior)
}

ENTITY_DEF_MERGE_START(CStateDefinition, ISlaveDefinition)
    MERGE_ARRAY_PROPERTY(IsHidden)
    MERGE_ARRAY_PROPERTY(DispelOnDamage)
    MERGE_ARRAY_PROPERTY(DispelOnAction)
    MERGE_ARRAY_PROPERTY(DisplayLevel)
    MERGE_ARRAY_PROPERTY(ImpactInterval)
    MERGE_ARRAY_PROPERTY(MorphPriority)
    MERGE_ARRAY_PROPERTY(NoRefresh)
    MERGE_ARRAY_PROPERTY(PropagateToIllusions)
    MERGE_ARRAY_PROPERTY(DeathPersist)
    MERGE_ARRAY_PROPERTY(ServerEntity)

    MERGE_TEMPORAL_PROGRESSIVE_ARRAY_PROPERTY(Armor)
    MERGE_TEMPORAL_PROGRESSIVE_ARRAY_PROPERTY(MoveSpeedSlow)
    MERGE_TEMPORAL_PROGRESSIVE_ARRAY_PROPERTY(MagicArmor)

    MERGE_ARRAY_MUTATION(Strength)
    MERGE_ARRAY_MUTATION(Agility)
    MERGE_ARRAY_MUTATION(Intelligence)

    MERGE_ARRAY_MUTATION(MaxHealth)
    MERGE_ARRAY_MUTATION(HealthRegen)
    MERGE_ARRAY_MUTATION(MaxMana)
    MERGE_ARRAY_MUTATION(ManaRegen)
    MERGE_ARRAY_MUTATION(Armor)
    
    MERGE_ARRAY_MUTATION(MagicArmor)
    MERGE_ARRAY_MUTATION(MoveSpeed)
    MERGE_ARRAY_MUTATION(SlowResistance)
    MERGE_ARRAY_MUTATION(AttackRange)
    MERGE_ARRAY_MUTATION(LifeSteal)
    MERGE_ARRAY_MUTATION(HealthRegenReduction)
    MERGE_ARRAY_MUTATION(ManaRegenReduction)
    
    MERGE_ARRAY_MUTATION(RevealRange)

    MERGE_STRING_VECTOR_ARRAY_MUTATION(UnitType)
    MERGE_RESOURCE_ARRAY_MUTATION(Icon)
    MERGE_RESOURCE_ARRAY_MUTATION(Portrait)
    MERGE_RESOURCE_ARRAY_MUTATION(Model)
    MERGE_RESOURCE_ARRAY_MUTATION(MapIconProperty)
    MERGE_ARRAY_MUTATION(MapIconColorProperty)
    MERGE_ARRAY_MUTATION(MapIconSizeProperty)
    MERGE_STRING_ARRAY_MUTATION(Skin)
    MERGE_STRING_ARRAY_MUTATION(AttackProjectile)
    MERGE_ARRAY_MUTATION(AttackType)
    MERGE_ARRAY_MUTATION(AttackEffectType)
    MERGE_ARRAY_MUTATION(AttackDamageType)
    MERGE_ARRAY_MUTATION(AttackCooldown)
    MERGE_ARRAY_MUTATION(AttackDuration)
    MERGE_ARRAY_MUTATION(AttackActionTime)
    MERGE_ARRAY_MUTATION(AttackTargetScheme)
    MERGE_ARRAY_MUTATION(AttackNonLethal)
    MERGE_ARRAY_MUTATION(ThreatEffectType)
    MERGE_ARRAY_MUTATION(ThreatScheme)
    MERGE_ARRAY_MUTATION(AggroRange)
    MERGE_ARRAY_MUTATION(AggroScheme)
    MERGE_ARRAY_MUTATION(ProximityRange)
    MERGE_ARRAY_MUTATION(ProximityScheme)
    MERGE_ARRAY_MUTATION(SightRangeDay)
    MERGE_ARRAY_MUTATION(SightRangeNight)
    MERGE_ARRAY_MUTATION(PreGlobalScale)
    MERGE_ARRAY_MUTATION(EffectScale)
    MERGE_ARRAY_MUTATION(ModelScale)
    MERGE_ARRAY_MUTATION(InfoHeight)
    MERGE_ARRAY_MUTATION(BoundsHeight)
    MERGE_ARRAY_MUTATION(BoundsRadius)
    MERGE_ARRAY_MUTATION(SelectionRadius)
    MERGE_MUTATION(IsSelectable)
    MERGE_MUTATION(NoCorpse)
    MERGE_ARRAY_MUTATION(AttackRangeBuffer)
    MERGE_ARRAY_MUTATION(AttackOffset)
    MERGE_ARRAY_MUTATION(TargetOffset)
    MERGE_RESOURCE_ARRAY_MUTATION(AttackStartEffect)
    MERGE_RESOURCE_ARRAY_MUTATION(AttackActionEffect)
    MERGE_RESOURCE_ARRAY_MUTATION(AttackImpactEffect)
    MERGE_RESOURCE_ARRAY_MUTATION(DeathEffect)
    MERGE_RESOURCE_ARRAY_MUTATION(PassiveEffect)
    MERGE_RESOURCE_ARRAY_MUTATION(SpawnEffect)

    MERGE_STRING_ARRAY_MUTATION(Inventory0)
    MERGE_STRING_ARRAY_MUTATION(Inventory1)
    MERGE_STRING_ARRAY_MUTATION(Inventory2)
    MERGE_STRING_ARRAY_MUTATION(Inventory3)
    MERGE_STRING_ARRAY_MUTATION(Inventory4)
    MERGE_STRING_ARRAY_MUTATION(Inventory5)
    MERGE_STRING_ARRAY_MUTATION(Inventory6)
    MERGE_STRING_ARRAY_MUTATION(Inventory7)
    MERGE_STRING_ARRAY_MUTATION(Inventory8)
    MERGE_STRING_ARRAY_MUTATION(SharedInventory0)
    MERGE_STRING_ARRAY_MUTATION(SharedInventory1)
    MERGE_STRING_ARRAY_MUTATION(SharedInventory2)

    MERGE_ARRAY_MUTATION(Invulnerable)
    MERGE_ARRAY_MUTATION(ClearVision)
    MERGE_ARRAY_MUTATION(Deniable)
    MERGE_ARRAY_MUTATION(DeniablePercent)
    MERGE_ARRAY_MUTATION(Smackable)
    MERGE_ARRAY_MUTATION(NoThreat)
    MERGE_ARRAY_MUTATION(TrueStrike)
    MERGE_ARRAY_MUTATION(AlwaysTransmitData)

    MERGE_ARRAY_MUTATION(Unitwalking)
    MERGE_ARRAY_MUTATION(Treewalking)
    MERGE_ARRAY_MUTATION(Cliffwalking)
    MERGE_ARRAY_MUTATION(Buildingwalking)
    MERGE_ARRAY_MUTATION(Antiwalking)

    MERGE_STRING_ARRAY_MUTATION(ShopAccess)
    MERGE_STRING_ARRAY_MUTATION(RemoteShopAccess)
    MERGE_STRING_ARRAY_MUTATION(SharedShopAccess)
    MERGE_STRING_ARRAY_MUTATION(SharedRemoteShopAccess)
    MERGE_STRING_ARRAY_MUTATION(RestrictItemAccess)
    MERGE_ARRAY_MUTATION(StashAccess)

    MERGE_ARRAY_MUTATION(DefaultBehavior)
ENTITY_DEF_MERGE_END

START_ENTITY_DEFINITION_XML_PROCESSOR(IEntityState, State)
    CStateDefinition::ReadSettings(pDefinition, node, bMod);
END_ENTITY_DEFINITION_XML_PROCESSOR(State, state)
